### ISSUE TITLE
Hallo! Wie funktioniert das alles hier?

### ISSUE THREAD

**Issue by chdoerr** [meisl/hafis#1]

**Comment by meisl** [comment]
Herzlich willkommen :)

**Comment by meisl** [comment]
**Wie macht man so ein ausdrückliches `#2` anstatt eines #2?** (Beispiel)
Antwort: man packt es zwischen zwei sog. backticks `` (Shift+die Taste links neben der Backspace-Taste rechts oben). Für `#2` schreibt man also
```
   `#2`
```

**Wie macht man denn sowas verrücktes wie "literal literals" da oben?!**
Antwort: oh... next level. Machen wir lieber später ;-)

**Comment by meisl** [comment]
**Wie macht man eine "task-list" mit Kästchen zum Abhaken?**
Antwort:
```
    - [ ] nicht abgehakt
    - [x] abgehakt
```
ergibt
- [ ] nicht abgehakt
- [x] abgehakt

**Comment by meisl** [comment]
**Wie kann ich Sachen ~durchstreichen~?**
Antwort: man packt das Durchzustreichende zwischen zwei Tilden `~`. Das geht auch mitten im Wort. Also:
```
   durch~gestrichen~
```
ergibt durch~gestrichen~

**Comment by chdoerr** [comment]
Aha
