### ISSUE TITLE
Wording: einheitliche Schreibweise/Abkürzungen

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#12]
Ergab sich aus #5, betrifft aber tatsächlich die gesamte Site.
TODO: übertrage wesentliche Punkte von #5 hierher.

* Schreibweisen
  - Zahlen von Null bis Zwölf, bzw. "zwölf Kinder", "drei Grundschulen", und dergleichen schreibt man normalerweise aus. Also nicht "12 Kinder", "3 Grundschulen". Bei Prozentwerten würde ich aber eine Ausnahme machen.
  - "50%" statt "50 Prozent" ("50 %", d.h. mit Leerzeichen ist einfach *falsch*)
  - **generell: KEIN Leerzeichen vor Interpunktion**
    * "Doppelpunkt:" statt "Doppelpunkt :"
    * "Punkt." statt "Punkt ."
    * "Komma," statt "Komma ,"
    * "Strichpunk; " statt "Strichpunkt ;"
    * "Fragezeichen?" statt "Fragezeichen ?"
    * "Ausrufezeichen!" statt "Ausrufezeichen !"
  - **Aber:** Leerzeichen vor und nach *Gedankenstrich* - sonst ist's ein Bindestrich
  - "Viertklässler" statt "4.Klässler"
* Abkürzungen
  - Abkürzungen, die ok sind:
    * "ggf." 
    * "Bsp."
    * "z.B."
  - Abkürzungen, die *zu diskutieren* sind:
    * "soz.päd." (auf `Warum systemische Lernhilfe?`)
    * "GS" für "Grundschule"
  - Abkürzungen, die **NICHT ok** sind:
    * "TN" (für "Teilnehmer", auf `Aktuell`)

**Comment by chdoerr** [comment]
@ meisl ok

**Comment by meisl** [comment]
Habe im OP angefangen zu sammeln. Denke aber jetzt **wir sollten ein Dokument im repo dafür machen**.
Es geht ja darum, wie (neue) Texte für die Website zu schreiben sind, und das soll ja weiter gelten.
Dieses Issue wird aber irgendwann geschlossen (wenn alle bisherigen Texte konform sind).

Das Dokument wäre so wie die READMEs, man könnte es also direkt im Browser lesen. Und Du könntest es übrigens auch direkt im Browser bearbeiten und dann committen (machen wir später).
Das Format wäre so wie in den Issues, d.h. bullet-lists, Überschriften etc. funktionieren genauso wie hier. Das Format heißt übrigens "Markdown", Dateiendung `.md`.

**Mögliche Namen**:
- [ ] `Wording.md` ("Denglish", aber prägnant)
- [ ] `Sprachregelung.md` (ohje...)
- [ ] `Schreibweisen.md` (äh... würg)
- [ ] `Texte auf der Website.md` (zu lang?)
- [ ] ???

Wat meinste?

**Comment by chdoerr** [comment]
@meisl Schreibweisen

**Comment by meisl** [comment]
Einverstanden. Sorry für das "würg", never mind :)

Ich hab jetzt nochmal im OP weitergeschrieben, anstatt es gleich anzulegen.
Möchte Dich ja schließlich nicht der Gelegenheit berauben, das selbst zu probieren. Anhand der Wiki-Seite [.md-Datei im repo erstellen/bearbeiten](https://github.com/meisl/hafis/wiki/.md-Datei-im-repo-erstellen-bearbeiten) (#13)
;-)

**Comment by meisl** [comment]
Bin nicht einverstanden mit der Schließung.
Ist nicht höchste Priorität, aber muss irgendwann gemacht werden. Ist einfach peinlich.
