### ISSUE TITLE
Issue-Labels

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#14]
Umbenannt:
* `Nice-to-have` -> `Nett`
* `Verschoben` -> `Später`

Gelöscht:
* `Hilfe!` (kann man "Frage" nehmen)
* `Gutes erstes Issue` (was damit markiert war gehört ins Wiki, sh. unten)

Neu:
* `Wiki`: *wir* benutzen das [Wiki](https://github.com/meisl/hafis/wiki) für "Basic-Tutorials" bzgl. github und Computer allgemein. Wenn also da was rein soll dieses Label. Beachte: das [Wiki](https://github.com/meisl/hafis/wiki) ist NICHT Teil des eigtl. repos (genausowenig wie die Issues).
* `Doku`: Dokumentation, die tatsächlich im eigtl. repo ist. Das wären Anleitungen/Maßgaben, die die Website selbst bzw. den Provider oder den Editor vom Provider betreffen.
  (*manche andere* benutzen dafür das [Wiki](https://github.com/meisl/hafis/wiki). *Wir nicht.*)

Vielleicht?:
* `Gestrichen` und `Ungültig` zusammenfassen zu `Obsolet`?
* `Verbesserung` ist mir persönlich irgendwie zu lang. Vielleicht `Feature`? Oder?

**Comment by meisl** [comment]
Noch was zum Label `Wiki`. Ich dachte mir das so:
* wenn (=sobald) *ich* meine, dass die entspr. Wiki-Seite fertig ist, tue ich das im zugeh. Issue kund.
* wenn *Du* dann alles auf der Wiki-Seite für verständlich, nachvollziehbar und vollständig hältst - schließt Du einfach das zugeh. Issue.
* wenn aber nicht - oder Du noch irgendwo ein "TODO" findest - sagst Du im zugeh. Issue Bescheid.

**Comment by chdoerr** [comment]
Was ist denn Wiki?

**Comment by meisl** [comment]
Na, das ist [wo ich die "Basic-Tutorials" mit den ganzen screenshots reintu](https://github.com/meisl/hafis/wiki) :-)

**Comment by meisl** [comment]
...und ich "assigne" Dich zu den `Wiki`-Issues, sobald ich sie für fertig halte. Damit Du's mitkriegst.

**Comment by chdoerr** [comment]
ja ja - aber was heißt wiki?

**Comment by meisl** [comment]
Also, **Wiki**pedia meint dazu: https://de.wikipedia.org/wiki/Wiki ;)

**Comment by meisl** [comment]
@chdoerr Würde das hier (Issue-Labels) gerne abschließen. Fasse mal zusammen:
- Umbenennungen sind OK für Dich
- Löschungen sind OK für Dich
- "Wiki" & "Doku" sind jetzt klar & OK
- Wir behalten "Verbesserung"
- "Gestrichen"/"Ungültig": wir brauchen sowas (bzw. werden es irgendwann brauchen), aber eigtl. nur eins davon. Es ist anders als "Später", nämlich insofern als dass es heißt "Vergiss es einfach - für immer!". *Warum dann nicht einfach ein solches Issue löschen?* Nun, das ist wieder für die Zukunft: wenn irgendwann wieder jemand damit ankommt, dann kann er das finden *bevor* es wieder "zum Issue" wird. Oder man kann drauf verweisen, dass oder warum es verworfen wurde.
Was nehmen wir also jetzt:
  - [ ] Gestrichen
  - [ ] Ungültig
  - [ ] Obsolet
  - [ ] Verworfen
  - [ ] irgendwas anderes kurzes, mit max. zwei Silben?

---
p.s.: Kannst auch gerne selbst die Labels ändern/löschen und dieses Issue dann schließen.

**Comment by meisl** [comment]
Ok, also "Obsolet". Mir ist einfach nix mit nur zwei Silben eingefallen...
Ich ändere die Labels.

---
p.s.: zwischen `@` und `meisl` darf kein Leerzeichen, sonst geht es nicht
