### ISSUE TITLE
Wiki: "Was ist ein Dateidialog?"

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#18]
Wiki-Seite: [Was ist ein Dateidialog?](https://github.com/meisl/hafis/wiki/Was-ist-ein-Dateidialog%3F)
(aufgekommen in #4)

**Comment by meisl** [comment]
@chdoerr Vielleicht könntest Du einfach mal nur diese eine Mini-Wiki-Seite anschauen, bitte?
Link: [Was ist ein Dateidialog?](https://github.com/meisl/hafis/wiki/Was-ist-ein-Dateidialog%3F)

Das Thema "Dateidialog" ist so dermaßen trivial - eigentlich war wohl nur der Begriff unbekannt (= das Ding als solches ist Dir schon begegnet)...
Kann mir echt nicht vorstellen, wie Dich das mehr als ein paar Minuten kosten kann. Danach dieses Issue einfach schließen.

---
p.s.: falls aber doch irgendeine Frage aufkommen sollte - habe mich ja schon öfter geirrt - dann einfach hier weiterschreiben. Wäre auch kein Problem.

**Comment by chdoerr** [comment]
okay
