### ISSUE TITLE
Setze/entferne div. Links

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#2]
- "Home":
  - [x] Weißensee-GS -> https://gsweiss.musin.de
  - [x] "eigene Bücher" -> "Mein fabelhaftes Deutschheft"
- [x] "Förderer": **keine** Links (da waren auch keine)
- [x] "Presse": Castringius-Stifung verlinken:
    der erste Newsletter von Castringius, Seite 6: http://castringius-stiftung-muenchen.de/images/stories/downloads/castringius_newsletter_10.pdf
- [x] "Aktuell": Link zu Castringius (sh. nächster Kommentar)

**Comment by meisl** [comment]
* auf "Aktuell", 23. Dezember 2011 war der Link auf die Castringius-Stiftung (vmtl. schon immer) **kaputt**
* dieser Link wurde Sat, 15 Sep 2018 17:29:21 komplett entfernt

**Frage: soll da der richtige Link hin oder gar keiner?**

**Comment by meisl** [comment]
[nur ein Test - bitte ignorieren]

**Comment by chdoerr** [comment]
Wir verlinken auf Aktuell genauso wie bei Presse
