### ISSUE TITLE
Aktuell: Bilder von allen Fußballturnieren (Schlachthof-/Schyren-Cups)

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#21]
Extrahiert aus #4 und #5. Dieses Issue ist klar umgrenzt - hätten wir gleich so machen sollen.
Tatsächlich sind mittlerweile genügend Bilder dafür da. Müssen teilw. noch auf die Website,
und relevante Refs hier gesetzt werden. Werde diesen OP entspr. updaten und unten abhaken.

Zu Format und Benennung sh. https://github.com/meisl/hafis/issues/4#issue-360640995

Soweit verfügbar wurden Exif-Daten erhalten bzw. angpasst (-> Exif-Orientation), sowie ein JPG-Kommentar gesetzt, der
1. das Event benennt
2. den Originaldateinamen in `[` und `]` enthält

---
**Achtung**: Nur weil alles so durcheinander und verstreut war/ist, unten nochmal komplett alle Bilder mit cross-refs. *Normalerweise würde man **nicht** so einen Aufwand treiben* - refs wie eben `#21` im commit-Kommentar reichten sonst völlig.

---
   v-- abgehakt heißt: online auf https://www.lernhilfe-hafis.de/aktuell **>>>** bei mehreren Optionen heißt "*diese* Option"
  - [x] 2013: zwei Motive, für Eintrag
        `18.07.2013 - Teilnahme am diesjährigen Schlachthof-Glockenbach-Fußball-Cup: Sieger im U-10- und 2.Platz im U-12-Wettbewerb !`
     * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2013-07-18_Schlachthof-Glockenbach-Cup2013_a.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2013-07-18_Schlachthof-Glockenbach-Cup2013_a.jpg)
        (orig. `dsc_0122.jpg`) aus https://github.com/meisl/hafis/issues/4#issuecomment-426549128
     *  [`MyWebsite/Bilder/Aktuell/Fussball/2013-07-18_Schlachthof-Glockenbach-Cup2013_b.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2013-07-18_Schlachthof-Glockenbach-Cup2013_b.jpg)
        (orig. `20130718_173715.jpg`) aus https://github.com/meisl/hafis/issues/4#issuecomment-426553610
        **ACHTUNG:** dieses Bild sei angeblich von 2014 - laut Metadaten (Exif) und Originalname ist es aber *offensichtlich vom selben Tag wie das erste*
![schlachthof-glockenbach-cup_2013_sheet_001](https://user-images.githubusercontent.com/1493886/46889363-bf37f600-ce63-11e8-833c-ce9389f7d139.jpg)

  - 2014 - haben wir keins, sh. oben. **Verschoben nach #30**

  - [x] 2015: **Original finde ich nicht mehr!** Für Eintrag
         `23.07.2015 - Unsere U10 gewinnt den Schyren-Cup 2015, im Finale besiegen wir Schülerfreiraum mit 7:2! Teilnehmende Mannschaften: Nachbarschaftstreff Westermühlbach, Rotznasen, Kubu, Konfetti, Isarkrabben, Schülerfreiraum und wir.`
     * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2015-07-23_Schyren-Cup2015.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2015-07-23_Schyren-Cup2015.jpg) ![MyWebsite/Bilder/Aktuell/Fussball/2015-07-23_Schyren-Cup2015.jpg](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2015-07-23_Schyren-Cup2015.jpg)

  - [x] 2016: 5 Motive in insges. 7 Originalen, aus https://github.com/meisl/hafis/issues/4#issuecomment-426550448 und folgende.  Für Eintrag
         `29.09.2016 - Gewinn des Schyren-Cups 2016: Die Titelverteidigung ist geglückt, Hafis gewinnt jedes Spiel. Die Teilnehmer in der Reihenfolge der Platzierung: Westermühlbach, Schülerfreiraum, Aardwaark, Konfetti, Isarkrabben und Rotznasen`
     Zur Auswahl stehen nun diese 8 Bilder:
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_a1.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_a1.jpg)
     * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_a2`.jpg](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_a2.jpg)
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_b.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_b.jpg)
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_c.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_c.jpg)
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_d1.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_d1.jpg)
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_d2.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_d2.jpg)
     * [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_e1.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_e1.jpg)
     * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_e2.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2016-09-29_Schyren-Cup2016_e2.jpg)
![2016-09-29_schyren-cup2016_sheet_001](https://user-images.githubusercontent.com/1493886/46908742-bf012e80-cf27-11e8-8d8a-8525b3882bcc.jpg)

  - [x] 2017: Ein Motiv, vier Varianten. Originale aus mail (original `schyrencup17.jpg`) und https://github.com/meisl/hafis/issues/4#issuecomment-426549793 (original `schyrencup 2017.jpg`). Für Eintrag
         `13.07.2017 - Schyren-Cup 2017: Das Triple ist geschafft, Hafis gewinnt zum dritten Mal nacheinander den Schyren-Cup. Im Finale besiegen wir Westermühlbach mit 3:0. Dritter wird Aardwaark, Vierter die Rotznasen und Fünfter unsere 2. Mannschaft (aus Ü1 und 2. und 3. Klasse) - dann kommen Konfetti, Isarkrabben und SFR.`
    * [`MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a0.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a0.jpg) (mail)
    * [`MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a1.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a1.jpg) (mail)
    * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a2.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a2.jpg) (mail)
    * [`MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a3.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a3.jpg) (https://github.com/meisl/hafis/issues/4#issuecomment-426549793)
![schyren-cup2017_sheet_001](https://user-images.githubusercontent.com/1493886/46947255-8c1b7f80-d07a-11e8-8cc2-ad242de3fe6d.jpg)

  - [x] 2018: Ein Motiv, zwei Varianten. Aus mail -> commit d63985a. Für Eintrag
         `11.07.2018 - Schyren-Cup 2018: Hafis gewinnt den U12 -Wettbewerb und wird Zweiter in der Altersgruppe U10 (Sieger Rotznasen, 2. Hafis,  3. Aadwaark, 4. Konfetti, 5. Westermühlbach, 6. Schülerfreiraum, 7. Isarkrabben)`
     * [`MyWebsite/Bilder/Aktuell/Fussball/2018-07-11_Schyren-Cup2018_a1.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2018-07-11_Schyren-Cup2018_a1.jpg)
     * **>>>** [`MyWebsite/Bilder/Aktuell/Fussball/2018-07-11_Schyren-Cup2018_a2.jpg`](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2018-07-11_Schyren-Cup2018_a2.jpg)
![schyren-cup2018_sheet_001](https://user-images.githubusercontent.com/1493886/46916747-f969da80-cfbe-11e8-9554-2c2f0c65c4a6.jpg)

**Comment by meisl** [comment]
@chdoerr So, bis 2016 ist alles schön benamst etc. im repo. Vllt. könnten wir schon mal anfangen, auszuwählen?

Dafür habe ich im OP sog. "Index-sheets" aus IrfanView reingetan (wie bei "Seefeld" in #4).
(-> in "Thumbnails" mehrere Bilder markieren | Rechtsklick | `Indexprint mit selektierte Bildern erstellen...`)
Wenn Du die Bilder in groß vergleichen willst, könntest Du per Rechtsklick | Bild in neuem Tab laden, und dann zwischen den Tabs hin und her.

---
- 2013: für mich klar Variante a (evtl. "faken" wir 2014 ja doch mit b...)
- 2014: haben wir keins
- 2015: haben wir nur eins, das ist aber ziemlich gut
- 2016: hier wird's interessant.
   - a: da hattest Du gesagt "vllt. nicht so toll" - ich find das aber super! Man spürt richtig die Freude und den Stolz von dem Mädel. Und das da noch jemand seinen "Daumen-runter" reinhält - und ein anderer (?) "Victory" - stört gar nicht. Im Gegenteil, das macht es erst richtig lebendig. Transportiert was chaotisches, und gleichzeitig "Triumph!". Die leichte Unschärfe verstärkt das IMHO sogar noch. a2 ist einfach ein klein wenig ein besserer Ausschnitt.
   - b: dieselbe Motividee wie a, auch ganz nett. Aber nicht so gut umgesetzt wie a, und zuviele Objekte abgeschnitten.
   - c: kann man vergessen, nix Interessantes zu sehen.
   - d: ist wieder "wir heben den Pokal", aber diesmal mit 4 Spielern (= besser). Allerdings ist d1 wohl inakzeptabel unscharf - und auf d2 schauen die Jungs eigentlich alle irgendwie doof (=gelangweilt, woanders hin...)
    - e: das Mannschaftsbild. Eigentlich *das* Motiv für so ein Turnier, nur dass es nicht den Sieg transportiert. e1 ist eigtl. der bessere shot, weil lebendig und lustig. Leider war da nicht mehr zu machen von wg. Qualität. e2 ist passabel, sowohl bzgl. Quali als auch "wie sie kucken". Zeigt schön den Mannschaftsaspekt - insbesondere da auch zwei Mädels dabei sind.
  Kannst ja mal raten, was mein Favorit wäre... **Was ist Deiner? Und warum?**

**Comment by meisl** [comment]
p.p.s.: nochmal zu 2016_a: wer genau hinschaut sieht, dass sowohl "Daumen runter" als auch "Victory" mit der *rechten* Hand gemacht werden. Kann also nicht dieselbe Person sein. Das merkt man aber erst auf den 2. oder 3. Blick - im 1. Moment fragt man sich "Wer? - Evtl. derselbe?!". Egal wie, das ist, was ich meine mit "lebendig", das ist Action!

**Comment by chdoerr** [comment]
Ich glaube mit Nieves ( dem Mädchen) hast Du rechtfür 2016 und es ist eigentlich auch mein favourite -
wenn Du meinst, dass Daumen runter nix macht.
Die zu viert bilder nur Jungs können wir vergessen
Das Mannschaftsfoto ist a bisserl langweilig stimmt schon, nicht ganz scharf - aber gerecht!
Vielleicht doch das letztere, das auch Dein Favorit ist ?

**Comment by meisl** [comment]
Also, mein Favorit für 2016 ist definitiv a2, mit Nieves (wg. "Daumen runter" etc. bin ich mir so sicher wie man da nur sein kann!). Meine zweite Wahl wäre das Mannschaftsfoto, e2, gewesen.
Ich glaub Du meinst wir sollten a2 nehmen, richtig?

Und für 2013 Variante, a - ok?

**Comment by meisl** [comment]
Hey, wir könnten für 2016 auch einfach zwei nebeneinander reinpacken. Ist dann zwar ein Einzelfall, aber was soll's schon...

**Comment by chdoerr** [comment]
Ja a für 2013
und - klar - warum nicht 2 Fotos nebeneinander !

**Comment by meisl** [comment]
@chdoerr Gut, dann noch 2017 und 2018:
* zuerst 2018, denn das hatten wir Sa ja schon angesprochen: a2 ist der bessere Ausschnitt
* 2017: das Motiv ist sehr schön, aber es gibt ein Problem mit dem Licht/den Farben. Hier muss man die Varianten wirklich in groß vergleichen.
  - [a0](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a0.jpg) ist das aus der mail, (von mir) unverändert. 
  - [a1](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a1.jpg) ist erstmal nur ein besserer Ausschnitt (nicht noch mehr von dem armen Jungen ganz rechts abschneiden...)
  - Für [a2](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a2.jpg) habe ich gleichzeitig Kontrast und gamma erhöht, damit der Bereich links oben "nicht so absäuft". Das ist besser als einfach alles nur heller zu machen.
  - [a3](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/Fussball/2017-07-13_Schyren-Cup2017_a3.jpg) ist dann das, was Du im Issue gepostet hattest. Das ist überschärft, finde ich. Schau z.B. auf die Jungs in der letzten Reihe, rechts im Bild. Die Köpfe wirken irgendwie unnatürlich vor dem Hintergrund. Wie ausgeschnitten und aufgeklebt. Auch in Deinem Gesicht sieht man ein komisches Artefakt, es sieht eckig aus.

  Plädiere für a2.

Ich pack die Sachen auf 1und1 und verwende auf der Website 2017_a2 und 2018_a2, die anderen Sachen wie besprochen. Wenn's mal oben ist, ist Austauschen kein großer Aufwand (ein paar Minuten).

**Comment by meisl** [comment]
Ist online. Wenn Du soweit mit der *Auswahl* zufrieden bist, würde ich dieses Issue gerne schliessen.

Die fehlenden Bilder von 2014 bitte in #30.

Zum Layout von Aktuell, insbesondere wie wir die Bilder da schön reinkriegen: das ist sicher noch nicht toll. Leider ist man recht beschränkt mit dem doofen Editor. Aber lass uns das bitte auch woanders diskutieren.

**Comment by chdoerr** [comment]
Die Auswahl ist gut - wir können schließen.

**Comment by meisl** [comment]
p.s.: hättest Du auch gerne gleich selbst schließen dürfen ("Close and comment"-Button). Keine Sorge, das hätte nicht komisch gewirkt oder sowas.
Wenn ich sage "ich würde das gerne schließen", dann geht es mir *nur* um's Schließen an sich, und überhaupt nicht darum, dass ich das selbst tun müsste. Nun, und da Du der einzige bist, nach dessen Einverständnis ich gefragt hatte...
