### ISSUE TITLE
#22 "Deutschheft": verbessere Text

### ISSUE THREAD

**Issue by chdoerr** [meisl/hafis#22]
@meisl 
Hi , habe ein neues issue ingeführt und auf der Homepage mehr Text in die Seite eingefügt

**Comment by meisl** [comment]
dupe of #6 (trotzdem super ;)

**Comment by meisl** [comment]
@chdoerr Oder war das so gedacht, dass die *Text*änderungen ein Issue für sich sein sollten?
Das wäre OK, aber dann müsste man 
* das im Issue-Titel sagen
* die relevanten Teile aus #6 dort wiederholen

**Comment by chdoerr** [comment]
@meisl Ja - so wars gedacht

**Comment by meisl** [comment]
Ok, sorry. Hab's umbenannt. Muss man noch bisschen aufräumen. Mach ich später, aber Du darfst natürlich auch, wenn Du willst.

**Comment by meisl** [comment]
Hmm... Also Du hast recht, es aufzusplitten ist gut. Aber anstatt alles jetzt aus #6 hierher zu tun - benennen wir das doch um. Bislang gings da eh nur um den Text. Für die Bilder hab ich #23 gemacht.
