### ISSUE TITLE
Aktuell: Bilder zur 10-Jahresfeier

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#28]
(extrahiert aus #4; im Namen von @chdoerr)

Für Eintrag
`26.01.2016 - Hafis wird 10 Jahre alt! Jubiläumsfeier in der Ittlinger-GS mit allen Sponsoren, Wegbegleitern, Förderern und Freunden: Der Tenor Michael Elliscasis singt Schubertlieder, Markus Nau erzählt eine Geschichte und unsere Ü1 trommelt.`

6 Originale: [10-Jahresfeier-Originale.zip](https://github.com/meisl/hafis/files/2476682/10-Jahresfeier-Originale.zip)

Die Bilder sind leider miserabel, aber wenn wir sie überarbeiten, könnte vielleicht noch etwas daraus werden.
Versuch' Dich dran und pack die Ergebnisse bitte in `MyWebsite/Bilder/Aktuell/10-Jahresfeier/`.

Zur Übersicht:
![10-jahresfeier-originale_sheet_001](https://user-images.githubusercontent.com/1493886/46920326-ea018600-cfec-11e8-8847-b1d8a8b9d9e6.jpg)

**Comment by chdoerr** [comment]
Ich werde wohl bis 4.November nicht dazu kommen
Gruß Christian

meisl <notifications@github.com> schrieb am So., 14. Okt. 2018, 20:18:

**Comment by meisl** [comment]
Also, *hier* gibt es für Dich erstmal nix zu tun.
Bitte lies Dir aber wenigstens einmal durch was ich in https://github.com/meisl/hafis/issues/4#issuecomment-429653267 zum Vorgehen geschrieben habe.

**Comment by meisl** [comment]
Na, ich weiß nicht...
Statt es einfach zu schließen - erledige ich das jetzt.
Die 6 Originale sind in [`Material/10-Jahresfeier/`](https://github.com/meisl/hafis/tree/master/Material/10-Jahresfeier), und diese beiden (Ausschnitte) packe ich auf die Website ([MyWebsite/Bilder/Aktuell](https://github.com/meisl/hafis/tree/master/MyWebsite/Bilder/Aktuell)):
![](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/2016-01-26_10-Jahresfeier_b_Ausschnitt.jpg)
![](https://github.com/meisl/hafis/raw/master/MyWebsite/Bilder/Aktuell/2016-01-26_10-Jahresfeier_d_Ausschnitt.jpg)

**Comment by chdoerr** [comment]
Wir wollten die Bilder nicht auf die HP stellen - die Qualität ist zu
schlecht.

meisl <notifications@github.com> schrieb am Sa., 21. Sep. 2019, 13:10:

**Comment by meisl** [comment]
Ich finde, es geht schon. Und ist besser als keine Bilder. Es ist immerhin ein Jubiläum.
Schau's dir an: https://www.lernhilfe-hafis.de/aktuell

Wenn du partout nicht willst, dann nehme ich sie wieder raus.
In jedem Fall können wir die Sache dann wirklich als abgeschlossen betrachten.

**Comment by chdoerr** [comment]
Na ja- Hauptsache der Issue ist zu.

meisl <notifications@github.com> schrieb am Sa., 21. Sep. 2019, 13:28:

**Comment by meisl** [comment]
Hast ja recht, es sind zuviele offen. Aber es wäre schon gut, kurz zu erklären *warum* ein Issue geschlossen wird. Auch ein "Lassen wir sein" wäre schon besser als nichts. Wir haben auch ein Label "Obsolet" (im Original: "wontfix"), das genau sowas ausdrücken soll.

Ich mache noch ein Site-Backup, und dann schließe ich das hier.

**Comment by meisl** [comment]
Fertig.
