### ISSUE TITLE
Layout: Navi+Inhalt so breit wie Balken unter Logo

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#3]
- [x] evtl.: Navi *links*bündig (-> wie sähe das aus?)
- [x] evtl.: Blocksatz überall (-> wie sähe das aus?)
- [x] ändere `MyWebsite/Design/CSS.txt`
- [ ] schreibe `MyWebsite/Design/README.md`: die Sache mit "Design" / "Style" in MyWebsite ist *teuflisch*! Sobald man Design speichert sind die Einstellungen in "Style" weg (zurückgesetzt)! Es ist aber möglich die Schriften in CSS ("Design") zu setzen - dann ist "Style" ohne Funktion...
- Plan:
![screenshot-home- 3-plan](https://user-images.githubusercontent.com/1493886/46178348-c6cd9b80-c2b6-11e8-83cf-0a2a88aed1fa.jpg)

**Comment by meisl** [comment]
Breite angepasst. Hier ein vorher/nachher-Vergleich (Navi rechtsbündig):
![screenshot-home- 3-vorher-nachher_navi-rechts](https://user-images.githubusercontent.com/1493886/46215721-608c5b80-c33e-11e8-888b-8bbc65672e26.jpg)

Vorher/nachher, diesmal mit Navi linksbündig:
![screenshot-home- 3-vorher-nachher_navi-links](https://user-images.githubusercontent.com/1493886/46215586-1014fe00-c33e-11e8-9327-47e460f217e0.jpg)

Schließlich noch mit Inhalt im Blocksatz. Zum Vergleich mit Navi links- und rechtsbündig:
![screenshot-home- 3-nachher-blocksatz_navi-links-rechts](https://user-images.githubusercontent.com/1493886/46215873-b9f48a80-c33e-11e8-9637-a9d9a26cfc48.jpg)

@chdoerr Bitte auf die Bilder draufklicken, dann siehst Du sie größer. Der Eindruck kann täuschen durch die Verkleinerung.
Was möchtest Du? (Bitte jeweils eins auswählen)
* Navi
  - [ ] linksbündig
  - [ ] rechtsbündig
* Inhaltstext
  - [ ] normal (=linksbündig)
  - [ ] Blocksatz

**Comment by chdoerr** [comment]
@meisl Danke

**Comment by meisl** [comment]
Und die Navi **rechtsbündig** (= so wie bisher, und wie es gerade online ist)?
Bin selbst durcheinandergekommen. Also so wie im screenshot ganz **rechts unten**?

**Comment by chdoerr** [comment]
@meisl Ja genau

**Comment by meisl** [comment]
Erledigt. Habe auch in Impressum den (früher) händisch eingefügten Blocksatz entfernt (wird jetzt alles zentral geregelt).

 (Doku ausgelagert nach #19).
