### ISSUE TITLE
Public Relations

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#31]
### Akut für Stadtratsbeschluss am 4. Dez. 2018 ###
Stadträte werden vorher recherchieren -> auch auf den Homepages der Grundschulen, mit denen Hafis kooperiert.
* Zusammenfassung Grundschul-HPs: [PR.md](https://github.com/meisl/hafis/blob/master/PR.md)
* Bei der Zusammenstellung ist mir aufgefallen: auf https://www.lernhilfe-hafis.de selbst findet man nirgendwo die genauen Betreuungszeiten. Auch ein Hinweis aufs Mittagsessen sowie auf Kosten bzw. die mögliche Befreiung davon findet sich nicht. Sowas könnten wir leicht selbst noch schnell reinpacken. Direkt auf die Einstiegsseite, oder - auch kein Problem - auf eine neue Unterseite.
* Bei manchen Grundschulen ist es nicht so leicht, die Stelle zu finden, an der Hafis erwähnt wird. Wir könnten selbst direkt auf die entsprechenden Stellen verlinken; sei es nun anstatt oder zusätzlich zu den Links auf die Einstiegsseiten der Grundschulen.

**Comment by chdoerr** [comment]
Wir geben nur an 2 Schulen Mittagessen aus: Ittlinger und Weissensee.
Bezahlt wird das von der Kindertafel Glockenbach, die das Geld an die Mensen der beiden Schulen spendet.

Die Ittlinger GS hat nun die 100 € gestrichen, mehr wollen sie anscheinend nicht machen.
Die GS Schererplatz hat ihre Seite inzwischen aufgefrischt, ein neues Foto kommt auch noch.

**Comment by meisl** [comment]
Mittagessen: ist soweit klar. Frage wäre, ob wir vielleicht selbst - auf www.lernhilfe-hafis.de - das aktuelle Angebot von Hafis detailliert beschreiben wollen?

[Ittlinger](http://www.gsittlinger.musin.de/cms/Betreuung/Hausaufgabenhilfe.html): die "100€" waren vorher schon weg, ist in PR.md gar nicht erst erwähnt. Schade ist halt der fehlende Link.

[Schererplatz](http://www.gs-scherer.musin.de/Schule/Foerder/Foerder.htm): das war - und ist nach wie vor - die Seite mit ganz viel Nichts und den nicht mehr aktuellen Stadtteilen. Welche "Auffrischung" meinst Du? Um was für ein Foto ging's da?

**Comment by chdoerr** [comment]
Hä -was für Stadtteile?

**Comment by chdoerr** [comment]
Das Mittagessen möchte ich nicht erwähnen- sonst müssen wir das überall machen....

Unter Auffrischung am Schererplatz verstehe ich: Dieses und letztes Schuljahr sind jetzt aufgeführt-
die letzte Aktualisierung ist eben im laufenden Schuljahr geschehen  und nicht vor 2 Schuljahren.

**Comment by meisl** [comment]
Stadtteile: sh. PR.md, unter Schererplatz/Details.
Mittagessen kann man natürlich auch weglassen. Trotzdem könnte man noch die Zeiten je Schule und Anzahl der Kinder genau nennen. War halt 'n Vorschlag, was wir *selbst* noch schnell hätten machen können.

**Comment by meisl** [comment]
Aktuell sehe ich 3 Punkte, die wir (jetzt) zu verbessern versuchen sollten:
* [Eduard-Spranger](http://www.ed-sprang.musin.de/index.php/kooperationspartner): dort steht nur "Hafis e.V.", sonst wirklich gar nix. Also Bitte um
  - "Lernhilfe Hafis e.V." statt "Hafis e.V."
  - Verlinkung (die anderen Einträge sind verlinkt)
  - ein paar beschreibende Stichworte wie bei den anderen. Beispiele:
    * "Systemische Lernhilfe für Kinder mit Migrations­hintergrund"
    * "Hausaufgabenbetreuung für internationale Schüler"
    * "Intensive Hausaufgaben- und Nachhilfe"
* [Schererplatz](http://www.gs-scherer.musin.de/Schule/Foerder/Foerder.htm)
  - wenigstens mal ansprechen wg. der komischen Seite, auf der erstmal ganz viel Nichts zu sehen ist
  - bei der Gelegenheit auch um Änderung des Textes bitten: "Lernhilfe Hafis e.V." statt "HAFIS", Name "Dörr" + Tel.-Nr., Stadtteile, evtl. Link?
* [Weissensee](https://gsweiss.musin.de/zusatzangebote)
  - Bitte um Austausch des Logos: [/Logo/Logo-klein.md](https://github.com/meisl/hafis/blob/master/Logo/Logo-klein.md) enthält einige deutlich bessere Varianten. Ich würde dieses vorschlagen:
    `/Logo/Logo_Hafis-2018_02c-klein.png`
    ![/Logo/Logo_Hafis-2018_02c-klein.png](https://github.com/meisl/hafis/raw/master/Logo/Logo_Hafis-2018_02c-klein.png)
  - Bitte um Verlinkungen des Logos (der Text "Lernhilfe Hafis e.V." ist bereits verlinkt)

**Comment by meisl** [comment]
Ok, also  `/Logo/Logo_Hafis-2018_02b-klein.png`
    ![/Logo/Logo_Hafis-2018_02b-klein.png](https://github.com/meisl/hafis/raw/875dde1ecf4f32e521e38e8ea2899c1ece5a4a73/Logo/Logo_Hafis-2018_02b-klein.png)

Wie ich sehe, ist es auch schon auf der Weissensee-HP, wenn auch (noch?) nicht verlinkt.

**Comment by meisl** [comment]
Verflixt nochmal: *das Ding auf Weissensee ist **wieder in jpg umgewandelt!***
Warum?!
![logo_hafis-2018_02b-klein](https://user-images.githubusercontent.com/1493886/49940279-61fe0680-fedf-11e8-8ec6-3146f7630805.jpg) `.jpg`
![logo_hafis-2018_02b-klein](https://user-images.githubusercontent.com/1493886/49940292-69251480-fedf-11e8-8c93-3937ef570b31.png) `.png`

@chdoerr Bitte überprüfe nochmal, ob Du den Grundschulen wirklich das png geschickt hast.

**Comment by chdoerr** [comment]
Ich habe an alle Schulen das png geschickt!

**Comment by meisl** [comment]
Also, die kommen da offenbar wirklich nicht klar bei der Weissensee.
Über's Wochenende war die Website down. Jetzt geht sie wieder, aber unser Logo ist immer noch das schlechte `.jpg`.
Wie gesagt, die meisten anderen sind auch `.png`s. Es gibt also keinen Grund, nicht auch unser besseres `.png` zu verwenden.
