### ISSUE TITLE
Alternative zu github: Bitbucket?

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#37]
Alternative zu github: [Bitbucket von Atlassian](https://bitbucket.org)

**Pro:**
- beliebig viele *private repos umsonst*
- bis zu 5 "User" umsonst
- unterstützt git-LFS: in Schritten von 10$/Monat/100GB (github: 5$/Monat/50GB)
- "file storage" bis 1 GB umsonst (etwas unklar sowohl bei Bitbucket als auch bei github; ich glaube es bezieht sich auch non-LFS Daten)
- günstigere "Pro"-Accounts:
  * 2$/Monat (mind. 5 user => ab 10$/Monat): beliebig viele User, 5 GB "file storage" inkl.
  * 5$/Monat (mind. 5 user => ab 25$/Monat): beliebig viele User, 10 GB "file storage" inkl.
- (ist nicht Microsoft - naja, ist das überhaupt ein Argument?)

**Contra:**
- mit github läuft's halt momentan - müssten uns in Einiges neu einarbeiten (nicht zu unterschätzen!)
- wie würden wir migrieren? **Insbesondere würden wir die Issues behalten wollen!**

----
Abgesehen davon wären aber vor einem evtl. Wechsel noch viele andere Fragen zu klären, z.B.:
- die Integration von Issues, Wiki, commit-comments ist bei github schon wirklich sehr gut. Kann Bitbucket da mithalten? Bzw. was davon würden wir tatsächlich vermissen?
- ist das Webinterface (= mit Browser drauf zugreifen) ähnlich einfach wie bei github?
- sind die Issues bzw. der Umgang damit ähnlich simpel wie bei github?
- haben sie auch ein REST-API?

### Fazit: ###
* Werde auf jeden Fall dort mal einen Account eröffnen und ein wenig herumprobieren, einfach aus Interesse/Neugier.
* Aber, @chdoerr: ist das für Dich überhaupt eine Frage? Also ich meine:
  - es ist zwar nicht auszuschließen, dass wir in Zukunft mehr "cloud storage" wollen/brauchen; so 50 GB oder 100 GB. Vllt. aber auch nicht...
  - aber: so ein Umstieg/eine Umgewöhnung bedeutet *viel* Aufwand!
  - angesichts dessen, und einer finanziellen Ersparnis von max. 20 €/Monat (*ganz* grobe Schätzung mit *sehr großem* "Sicherheitsabstand" nach oben, d.h. *eher weniger!*) - **nehme ich schwer an, dass für Dich eine genauere Recherche erst gar nicht lohnenswert erscheint. Richtig?**

**Comment by chdoerr** [comment]
Bin nicht dafür....

**Comment by meisl** [comment]
Wow - das war aber eine *schnelle* Antwort!
Dachte ich mir schon, aber natürlich will ich Dir auch Alternativen aufzeigen :)
Also schließe ich dieses Issue gleich wieder; für eventuelle weitere Erkenntnisse zu Bitbucket würde ich es ggf. wieder öffnen.
