### ISSUE TITLE
Schyren-Cup 2019 (17.07.2019)

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#38]
Das war ein toller Tag heute!

Ich hab' das Foto von den Ergebnissen in [Material/Schyren-Cup/2019/](https://github.com/meisl/hafis/tree/master/Material/Schyren-Cup/2019) eingecheckt.

@chdoerr:
- [x] *möglichst viele* Fotos von heute ebenso unter [Material/Schyren-Cup/2019/](https://github.com/meisl/hafis/tree/master/Material/Schyren-Cup/2019) einchecken
- [x] insbesondere auch das von Tiziana: Gruppenbild am Ringerstandbild
- [x] hier (in diesem Issue) schreiben, welche du am besten findest: https://raw.githubusercontent.com/meisl/hafis/master/Material/Schyren-Cup/2019/IMG-20190717-WA0004_a.jpg
- [ ] ein Bild fehlt: `20190717_182152.jpg` (sh. 04cee800239d8f6aaf4ed30b8982c92ef590ed6d)

Einchecken kannst du die Bilder rein im Browser: auf den Link oben klicken, dann auf den "Upload Files"-Button und die Bilder reinziehen. Im commit-Kommentar schreiben: `+ #38: Bilder vom Schyren-Cup 2019`

@meisl:
- [ ] Spielplan mit allen Ergebnissen in digitaler Form
- [ ] plus Endstandstabelle mit Punkten, Toren, G/U/V
- [x] 1 oder 2 Fotos aufbereiten für Website: https://raw.githubusercontent.com/meisl/hafis/master/Material/Schyren-Cup/2019/IMG-20190717-WA0004_a.jpg

TODO:
- [x] Text und aufbereitete Fotos bei 1&1 unter "Aktuell" einpflegen
- [x] Korrekturen auf der (gesamten) Aktuell-Seite:
       * ~~Aadwaak~~ `->` Aardvark
       * ~~Westermühlbach~~ `->` Westermühlenbach
- [x] danach: Website-Backup: e790bcd3e6e181049a7930f556cc2b71de85a973

### Textvorschlag (endgültig: https://github.com/meisl/hafis/issues/38#issuecomment-530987762)
> 17.07.2016 - Schyren-Cup 2019
> Dieses Jahr wurde das Turnier im Liga-Modus ausgetragen, und die U-10 Mannschaft
> von Hafis verliert nur ein Spiel von sieben: gegen den späteren Turniersieger - 2. Platz!
> Die Platzierungen: 1. Westermühlenbach, 2. Hafis, 3. Aardvark, 4. Konfetti, 5. Rotznasen, 6. Isarkrabben, 7. Schülerfreiraum, 8. KuBu.
> Im U12-Wettbewerb traten diesmal nur zwei Mannschaften an:  Schülerfreiraum und Freie Gruppe.

Bei U-12 weiß ich leider den Endstand nicht - und nicht mal, ob sie da nur ein Spiel à 2x 10min gemacht haben oder zwei. @chdoerr: Joel fragen.

**Comment by meisl** [comment]
Achtung: Schyren-Cup 2019 ist Issue #38, NICHT ~~#37~~ wie ursprünglich im OP.

**Comment by meisl** [comment]
To be clear:
Sobald ich *ein* brauchbares Foto habe, würde ich die Website aktualisieren.
(Passwort habe ich wieder vergessen 8-}, sagst du mir morgen persönlich)

**Comment by chdoerr** [comment]
![IMG-20190717-WA0010](https://user-images.githubusercontent.com/40777919/61470650-c6a3a700-a981-11e9-907a-e0b529ade405.jpg)
![IMG-20190717-WA0008](https://user-images.githubusercontent.com/40777919/61470651-c6a3a700-a981-11e9-8755-a7d8fea96035.jpg)
![IMG-20190717-WA0009](https://user-images.githubusercontent.com/40777919/61470652-c73c3d80-a981-11e9-95cc-1d007c34973e.jpg)
![IMG-20190717-WA0007](https://user-images.githubusercontent.com/40777919/61470653-c73c3d80-a981-11e9-81d0-a12ab07cf215.jpg)
![IMG-20190717-WA0006](https://user-images.githubusercontent.com/40777919/61470654-c73c3d80-a981-11e9-9359-8f1baa797ace.jpg)
![IMG-20190717-WA0005](https://user-images.githubusercontent.com/40777919/61470657-c7d4d400-a981-11e9-8f41-c9af55019260.jpg)
![IMG-20190717-WA0004](https://user-images.githubusercontent.com/40777919/61470658-c7d4d400-a981-11e9-8f39-4186ad12eeb1.jpg)
![IMG-20190717-WA0003](https://user-images.githubusercontent.com/40777919/61470659-c7d4d400-a981-11e9-90b6-b2525f1f9463.jpg)
![IMG-20190717-WA0002](https://user-images.githubusercontent.com/40777919/61470660-c86d6a80-a981-11e9-9e17-56e6f6ab03ad.jpg)
![IMG-20190717-WA0001](https://user-images.githubusercontent.com/40777919/61470661-c86d6a80-a981-11e9-90a6-afdabc86682e.jpg)
![20190717_182706](https://user-images.githubusercontent.com/40777919/61470662-c86d6a80-a981-11e9-979f-43335c92e6e6.jpg)
![20190717_182704](https://user-images.githubusercontent.com/40777919/61470664-c9060100-a981-11e9-996c-88f1eff3d405.jpg)
![20190717_182703](https://user-images.githubusercontent.com/40777919/61470667-c9060100-a981-11e9-852f-46e9de75046a.jpg)
![20190717_182701](https://user-images.githubusercontent.com/40777919/61470668-c9060100-a981-11e9-9b3b-f0ba05f36df0.jpg)
![20190717_182657](https://user-images.githubusercontent.com/40777919/61470670-c99e9780-a981-11e9-894a-c5677606be9c.jpg)
![20190717_182655](https://user-images.githubusercontent.com/40777919/61470671-c99e9780-a981-11e9-8097-084ddabb310d.jpg)
![20190717_182651](https://user-images.githubusercontent.com/40777919/61470672-c99e9780-a981-11e9-96c4-0ad68f02703d.jpg)
![20190717_182650](https://user-images.githubusercontent.com/40777919/61470673-c99e9780-a981-11e9-9100-f97d96cc1752.jpg)
![20190717_182649](https://user-images.githubusercontent.com/40777919/61470674-ca372e00-a981-11e9-93ed-61db1ae3205b.jpg)
![20190717_182648(0)](https://user-images.githubusercontent.com/40777919/61470676-ca372e00-a981-11e9-9507-5ca31ba42171.jpg)
![20190717_182648](https://user-images.githubusercontent.com/40777919/61470677-ca372e00-a981-11e9-957b-f1b23e049c48.jpg)
![Uploading 20190717_182647.jpg…]()
![Uploading 20190717_182646.jpg…]()
![Uploading 20190717_182645.jpg…]()
![Uploading 20190717_182644.jpg…]()
![Uploading 20190717_182642.jpg…]()
![Uploading 20190717_182333.jpg…]()
![Uploading 20190717_182330.jpg…]()
![Uploading 20190717_182327.jpg…]()
![Uploading 20190717_182235.jpg…]()
![Uploading 20190717_182209.jpg…]()
![Uploading 20190717_182205.jpg…]()
![Uploading 20190717_182158.jpg…]()
![Uploading 20190717_182152.jpg…]()
![Uploading 20190717_182144.jpg…]()

**Comment by meisl** [comment]
Danke für's prompte Hochladen - bzw. den Versuch... ;)
Ich hatte im OP geschrieben:

> möglichst viele Fotos von heute ebenso unter [Material/Schyren-Cup/2019/](https://github.com/meisl/hafis/tree/master/Material/Schyren-Cup/2019) einchecken
> ...
> Einchecken kannst du die Bilder rein im Browser: auf den Link oben klicken, dann auf den "Upload Files"-Button und die Bilder reinziehen. Im commit-Kommentar schreiben: + #38: Bilder vom Schyren-Cup 2019

Du hast sie stattdessen in diesem Issue gepostet. Abgesehen davon, dass sie so *nicht* im repo sind (nur im Issue), gibt es da auch eine Begrenzung. Schau mal oben. Für die letzten 14 hat es nicht mehr funktioniert.
Bitte probiere diese wirklich einzuchecken. So wie ich es beschrieben habe. Ist genauso einfach wie hier posten.
Es ist nämlich so: wenn sie im repo sind, dann kann ich ein contact-sheet machen wie bei Melusinen, und wir können komfortabel aussuchen und vergleichen.

**Comment by meisl** [comment]
Na, geht doch: e255abd2400cb8f1546ac9e1fd3356ba1ef7162a
Wenn du auch den vorgeschlagenen commit-Kommentar verwendetet hättest, dann hätte ich's auch gleich mitbekomment.

**Comment by chdoerr** [comment]
Text ist gut, das einzig [verbesserte Bild](https://raw.githubusercontent.com/meisl/hafis/master/Material/Schyren-Cup/2019/IMG-20190717-WA0004_a.jpg) ist gelungen.
Lass besser den U12 -Beitrag  ( ist eh nur ein Satz) weg!

**Comment by meisl** [comment]
Wird gemacht, zusammen mit #39.

Allerdings:
- [ ] idealerweise würde ich vorher noch einen "Abzug" vom aktuellen Stand machen (-> `mirror-wget`)
- [ ] auf jeden Fall aber *nach* diesen beiden Änderungen
- dafür muss ich mich erst wieder "reinfuchsen" in das Thema - ist leider nicht einfach ein repo wie www.christiandörr.de (repo: `chdoerr.github.io` / fork: `meisl.github.io/chdoerr.github.io`)
- [ ] *dieses* Issue muss ich nochmal durchgehen. Bin mir nicht sicher, ob alles Material jetzt nun wirklich im repo ist, oder nur hier, oder...

Ich versuche es baldmöglichst online zu bringen. Auf jeden Fall noch diese Woche, versprochen.
