### ISSUE TITLE
Link zu www.christiandörr.de auf "Initiatoren" setzen

### ISSUE THREAD

**Issue by chdoerr** [meisl/hafis#39]

**Comment by meisl** [comment]
sh https://github.com/meisl/hafis/issues/38#issuecomment-529236233

**Comment by meisl** [comment]
@chdoerr schrieb in https://github.com/chdoerr/chdoerr.github.io/issues/22#issuecomment-533686527
> Vielleicht sollten wir aus D
> Datenschutzgründen meine HP  von der
> Vereinsseite wieder runternehmen.
> Das Ganze erscheint mir nicht koscher...

**Comment by meisl** [comment]
Ich seh' da eigentlich kein Problem. 
Aber ok, wenn du meinst.
Dann mache ich den Link dort nach www.christiandörr.de wieder raus.

**Comment by meisl** [comment]
Link zu www.christiandörr.de wieder entfernt von www.lernhilfe-hafis.de/die-initiatoren

Ein extra Site-Backup habe ich dafür nicht gemacht. Lohnt nicht - zumal ich so ein Gefühl habe,
dass sich das auch bald wieder ändern könnte... ;)

---

War neben dem Bild ganz unten:
> Christian Dörrs private Homepage:
> www.christiandörr.de

unterhalb von
> Petra Cordua und Christian Dörr
>
> Kontakt:
> christiandoerr67@gmail.com
