### ISSUE TITLE
"Initiatoren": chdoerrs email mit "mailto:"-Link?

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#40]
Sh. auch #39

### Wo?
Auf https://www.lernhilfe-hafis.de/die-initiatoren steht ganz unten, rechts neben dem Bild:
```
Petra Cordua und Christian Dörr

Kontakt:
christiandoerr67@gmail.com
```

### Was?
* Die email-Adresse, `christiandoerr67@gmail.com` ist derzeit einfach nur ein Text, nicht anklickbar.
* Ein sog. **"mailto:"-Link** würde beim Draufklicken den email-Client öffnen (Thunderbird, Google-mail, whatever), mit schon eingetragener Empfängeradresse; und **optional: auch vorgegebenem Betreff**.
* Es wäre wie der "Kontakt"-Button auf www.christiandörr.de

### Frage:
* Soll ich die email-Adresse auf www.lernhilfe-hafis.de/die-initiatoren so anklickbar machen wie den "Kontakt"-Button auf www.christiandörr.de ?
* Möchtest du einen vorgegebenen Betreff? Bsp.: `lernhilfe-hafis.de: `. Die Leute könnten dann dahinterschreiben, worum es ihnen im Detail geht.

**Comment by chdoerr** [comment]
Ja -gute Idee

**Comment by meisl** [comment]
Und Betreff vorgeben?

Z.B.: `lernhilfe-hafis.de: ` könnte *dir* helfen, deine email zu sortieren.
Natürlich können die Leute aber auch das Vorgegebene löschen und was komplett anderes im Betreff schreiben. Wäre mehr so eine Art "Leitplanke".

?

**Comment by meisl** [comment]
Ok, ist entspr. verlinkt, vorgegebener Betreff ist: `www.lernhilfe-hafis.de: `
Probier's selbst mal aus:
* https://www.lernhilfe-hafis.de/die-initiatoren/
* dann unten auf die email-Adresse klicken
* es sollte sich dein email-Client öffnen, um eine neue email zu schreiben, mit vorgegebenem Empfänger und Betreff

#### Passt das so?

Wenn ja: dieses Issue einfach schließen.

___
p.s.: sh. https://blog.kulturbanause.de/2012/01/e-mail-links-mailto-mit-betreff-kopie-cc-blindkopie-bcc-und-nachrichteninhalt/

**Comment by meisl** [comment]
Na, ich denke es ist ok. Haben wir schließlich bei "Mein fabelhaftes Deutschheft" genauso.
